# Generated by Django 2.2.3 on 2019-08-07 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Address', models.CharField(blank=True, max_length=500, null=True)),
                ('Phone_no', models.CharField(max_length=11)),
                ('Degree', models.CharField(max_length=100)),
                ('Gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=100, null=True)),
                ('Time', models.CharField(max_length=100)),
                ('Room_no', models.CharField(max_length=10)),
                ('Fees', models.PositiveIntegerField()),
                ('Specialized', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.DoctorCategory')),
            ],
        ),
    ]
