# Generated by Django 2.2.3 on 2019-08-17 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0003_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetails',
            name='Short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
